'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FHT59N3.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cooling_off_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cooling_off_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cooling_on_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cooling_on_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GreenDot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenDot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RedDot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedDot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stock_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stock_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stock_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stock_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;N42InstrumentData 
        '''	xmlns=&quot;http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2005/ANSIN4242&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; 
        '''	xmlns:sara=&quot;http://www.technidata.com/ENVINET/SARA&quot; xmlns:fht=&quot;http://www.thermofisher.com/DivisionSpectro/FHT59N3/ANSI4242/V1&quot;
        '''	xmlns:n42_2012=&quot;http://physics.nist.gov/Divisions/Div846/Gp4/ANSIN4242/2011/ANSIN4242&quot;&gt;
        '''	
        '''  &lt;Measurement ID=&quot;{{measurement_id}}&quot;&gt;
        '''		&lt;InstrumentInformation&gt;
        '''			&lt;InstrumentType&gt;Spectr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TEMPLATE_SPECTRA_ANALYSIS_ANSI4242() As String
            Get
                Return ResourceManager.GetString("TEMPLATE_SPECTRA_ANALYSIS_ANSI4242", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property TEMPLATE_SPECTRA_ANALYSIS_CSV() As String
            Get
                Return ResourceManager.GetString("TEMPLATE_SPECTRA_ANALYSIS_CSV", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ThermoScientificSoftware() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThermoScientificSoftware", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ThermoScientificSoftware_Stacked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ThermoScientificSoftware_Stacked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TS_LOGO_TRANS_V1_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TS_LOGO_TRANS_V1_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property YellowDot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("YellowDot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Zoom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zoom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
